import fs from 'fs/promises';
import * as path from 'path';

/**
 * Configuration object
 */
export const CONFIG = {
  OUTPUT_DIR: process.env.BACKUP_OUTPUT_DIR,
  API_DELAY: 400, // ~3 req/sec to respect Notion rate limits
  MAX_FILENAME_LENGTH: 100,
  PARALLEL_PROCESSING: false, // Process child pages in parallel
  CLEAN_OUTPUT: true, // Clean output directory before backup
  LOG_LEVEL: ['debug', 'info'].includes(process.env.LOG_LEVEL)
    ? process.env.LOG_LEVEL
    : 'debug' 
};

/**
 * Statistics tracker
 */
export const stats = {
  pagesProcessed: 0,
  errors: 0,
  startTime: Date.now()
};

/**
 * Logger utility
 */
export const log = {
  info: (msg) => console.log(`ℹ️ ${msg}`),
  success: (msg) => console.log(`✅ ${msg}`),
  warn: (msg) => console.warn(`⚠️ ${msg}`),
  error: (msg) => console.error(`❌ ${msg}`),
  debug: (msg) => {
    if (CONFIG.LOG_LEVEL === 'debug') console.log(`🔍 ${msg}`);
  }
};

/**
 * Sleep utility for rate limiting
 * @param {number} ms - Milliseconds to sleep
 */
export async function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Sanitize filename for filesystem compatibility
 * @param {string} title - Raw title from Notion
 * @returns {string} Sanitized filename
 */
export function sanitizeFilename(title) {
  if (!title || title.trim() === '') return 'Untitled';
  
  return title
    .trim()
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, CONFIG.MAX_FILENAME_LENGTH) || 'Untitled';
}

/**
 * Ensure directory exists, create if necessary
 * @param {string} dirPath - Directory path to ensure
 */
export async function ensureDir(dirPath) {
  try {
    await fs.mkdir(dirPath, { recursive: true });
    log.debug(`Ensured directory exists: ${dirPath}`);
  } catch (error) {
    log.error(`Failed to create directory ${dirPath}: ${error.message}`);
    throw error;
  }
}

/**
 * Generate YAML frontmatter for markdown file
 * @param {string} title - Page title
 * @param {string} pageId - Notion page ID
 * @param {string} parentPath - Parent directory path
 * @param {number} level - Nesting level
 * @returns {string} Formatted frontmatter
 */
export function generateFrontmatter(title, pageId, parentPath, level) {
  const now = new Date().toISOString();

  const includeExported = false;

  return `---
title: "${title.replace(/"/g, '\\"')}"
notion_id: "${pageId}"
${includeExported ? `exported_at: "${now}"` : ''}
path: "${parentPath}"
level: ${level}
---

`;
}

/**
 * Generate backup index file
 * @param {string} rootPageId - Root page ID
 */
export async function generateIndex(rootPageId) {
  const indexPath = path.join(CONFIG.OUTPUT_DIR, 'INDEX.md');
  const duration = ((Date.now() - stats.startTime) / 1000).toFixed(2);
  
  const includeDate = false;
  const includeDuration = false;

  const indexContent = `# Notion Backup Index

## Backup Information

${includeDate ? `- **Date**: ${new Date().toISOString()}` : ''}
- **Root Page ID**: \`${rootPageId}\`
${includeDuration ? `- **Duration**: ${duration}s` : ''}
- **Processing Mode**: ${CONFIG.PARALLEL_PROCESSING ? 'Parallel' : 'Sequential'}

## Statistics

- ✅ Pages processed: ${stats.pagesProcessed}
- ❌ Errors: ${stats.errors}

## Configuration

- API Delay: ${CONFIG.API_DELAY}ms
- Parallel Processing: ${CONFIG.PARALLEL_PROCESSING}

---
*Generated by [notion-recursive-backup](https://github.com/vincenzoarico/notion-recursive-backup)*
`;

  await fs.writeFile(indexPath, indexContent, 'utf8');
  log.success('Generated backup index');
}

/**
 * Print summary statistics
 */
export function printSummary(rootPageId) {
  console.log('\n╔════════════════════════════════════════╗');
  console.log('║   Backup Completed Successfully! 🎉    ║');
  console.log('╚════════════════════════════════════════╝\n');
  
  const duration = ((Date.now() - stats.startTime) / 1000).toFixed(2);
  const avgSpeed = stats.pagesProcessed / (duration / 60);
  
  console.log(`📊 Summary:`);
  console.log(`   • Root Page ID: ${rootPageId}`);
  console.log(`   • Pages processed: ${stats.pagesProcessed}`);
  console.log(`   • Errors: ${stats.errors}`);
  console.log(`   • Duration: ${duration}s`);
  console.log(`   • Avg speed: ${avgSpeed.toFixed(1)} pages/min`);
  
  if (stats.errors > 0) {
    log.warn(`${stats.errors} fatal error(s) occurred. Some pages may be incomplete.`);
  }
}
